version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
    - 5555:5432
    volumes:
    - ./data:/var/lib/postgresql/data
    - ./sedeloger_tables.sql:/docker-entrypoint-initdb.d/script-tpl.sql
    env_file:
    - docker.env
    networks:
    - nlpf2_net

networks:
  nlpf2_net:
    driver: bridge